name: sauna_meshi
description: A new Flutter project.
publish_to: "none"

version: 1.1.0+2

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.5
  geolocator: ^7.7.0
  http: ^0.13.5
  permission_handler: ^10.2.0
  flutter_compass: ^0.7.0
  url_launcher: ^6.1.10
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/map_style.json
    - assets/restaurant_pin.png
    - assets/splash.png
    - assets/icon.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
